### ISSUE TITLE
Difference from bwapi-rs

### ISSUE THREAD

**Issue by nlinker** [Bytekeeper/rsbwapi#1]
Hello,

Cannot find the address how do I write a letter to you, hence I've created the issue.

There is a project https://github.com/RnDome/bwapi-rs which aims to be an API for bots written in Rust.
I just wondering, is this project fixes some issues about it or takes completely different direction?
If there were issues, could you describe them?

Thank you!

**Comment by Bytekeeper** [comment]
Hi!  
I am aware of that project. But it is pretty much incomplete, basic API like building or researching seems to be missing.
I must have been a huge undertaking, considering that BWAPI was ported to C to make the bindings work.

This repo, however, implements a BWAPI client. This basically allows:
* Easier development in Linux
* Having 64bit bot binaries
* Potential compatibility with OpenBW, without porting its BWAPI version to C as well

Also, bwapi-rs hides some unsafety - for example it is possible to access Units after submitting a frame, and thus modify or access the state while the server is processing.
I'm not saying this is cause for not using it. This project was also meant to learn Rust better, and I have experience with the Java port of BWAPI (https://github.com/JavaBWAPI/JBWAPI).

If you want to write a bot or are generally interested in Broodwar AI, I recommend joining our discord at https://discord.gg/NHfmzCSp - it has a small but very competent community of developers and people interested in AI.

I hope that answers your questions, if not - shoot :)

**Comment by nlinker** [comment]
> I must have been a huge undertaking, considering that BWAPI was ported to C to make the bindings work.

Yeah, it was forced since the original BWAPI is very tight to C++, we didn't see a way other than to create C wrapper around BWAPI and then start to build Rust api over C-api.
I'm glad you've found an alternative way to avoid this intermediate step 👍 

> discord.gg
I'm in :-)

**Comment by nlinker** [comment]
Thanks, closing.
